<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net10.0-windows;net11.0-windows</TargetFrameworks>
    <Company>新生命开发团队</Company>
    <Copyright>©2002-2023 NewLife</Copyright>
    <VersionPrefix>1.0</VersionPrefix>
    <VersionSuffix>$([System.DateTime]::Now.ToString(`yyyy.MMdd`))</VersionSuffix>
    <Version>$(VersionPrefix).$(VersionSuffix)</Version>
    <FileVersion>$(Version)</FileVersion>
    <AssemblyVersion>$(VersionPrefix).*</AssemblyVersion>
    <Deterministic>false</Deterministic>
    <OutputPath>..\Bin\WinModbus</OutputPath>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DH.NCore" Version="4.25.2026.911-beta0202" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DH.NModbusRTU\DH.NModbusRTU.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="FrmI6O6N.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="InputPort.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>

</Project>